### ISSUE TITLE
panic cleaning up repository data when multiple deps specify a single sub-repo

### ISSUE THREAD

**Issue by erikh** [LK4D4/vndr#14]
I used this script to generate the deps for vndr from containers/image. What I believe is happening is that several goroutines are trying to update the same directory at the same time, which is causing your filepath.Walks to fail.

All the data that I have is in the ticket, I think.

```bash
#!/bin/bash

set -e

list() {
  (for i in $(go list $1 | xargs go list -f '{{ join .Deps "\n" }}' | grep -v github.com/containers/image | grep -v $GOPATH | sort | uniq)
  do
    if [ -d "$(go env GOROOT)/src/${i}" ]
    then
      continue
    else
      echo $i
    fi
  done) | sort | uniq
}

lastlist=""
echo 1>&2 -n Listing package...
mylist=$(list ./...)
echo 1>&2 done.

while [ "$lastlist" != "$mylist" ]
do
  # cancel out error mask below
  set -e
  lastlist=$mylist
  for i in $mylist
  do
    echo 1>&2 Processing deps for dependency "'$i'"

    if [ -d ${GOPATH}/src/${i} ]
    then
      continue
    else
      set +e
      go get -d $i
      if [ $? != 0 ]
      then
        # pad it to keep the loop running, we'll grep it out later.
        # the important thing is that we do not execute list here which will
        # break
        mylist=$(echo -e "$lastlist\n")
        continue
      fi
    fi

    echo 1>&2 -n Listing $i ...
    innerlist=$(list $i)
    echo 1>&2 done.
    mylist=$(echo -e "$lastlist\n$innerlist" | sort | uniq)
  done
done

echo 1>&2 Filtering dependency list...
(
for i in $mylist
do
  echo $i master
done
) | sort | uniq
```

panic on latest master:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4051a5]

goroutine 50 [running]:
panic(0x701040, 0xc42000c100)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.cleanVCS.func1(0xc420061320, 0x59, 0x0, 0x0, 0x8b07c0, 0xc4205e0ff0, 0x0, 0x0)
        /home/erikh/src/github.com/lk4d4/vndr/clean.go:142 +0x35
path/filepath.walk(0xc420408900, 0x51, 0x8b6080, 0xc4206d6dd0, 0x7810b8, 0x0, 0xc420408a80)
        /usr/local/go/src/path/filepath/path.go:372 +0x22e
path/filepath.Walk(0xc420408900, 0x51, 0x7810b8, 0x0, 0x56)
        /usr/local/go/src/path/filepath/path.go:398 +0xd5
main.cleanVCS(0xc42038e3f0, 0x28, 0x0)
        /home/erikh/src/github.com/lk4d4/vndr/clean.go:153 +0x110
main.cloneDep(0xc420403d80, 0x32, 0xc42010eb70, 0x28, 0xc42010eb99, 0x6, 0x0, 0x0, 0x0, 0x0)
        /home/erikh/src/github.com/lk4d4/vndr/clone.go:101 +0x3c2
main.cloneAll.func1(0xc420061da0, 0xc420061d40, 0xc420403d80, 0x32, 0xc4203d05a0, 0xc42010eb70, 0x28, 0xc42010eb99, 0x6, 0x0, ...)
        /home/erikh/src/github.com/lk4d4/vndr/clone.go:71 +0x83
created by main.cloneAll
        /home/erikh/src/github.com/lk4d4/vndr/clone.go:74 +0x1ac
```

vendor.conf:

```
github.com/containers/storage/drivers/aufs master
github.com/containers/storage/drivers/btrfs master
github.com/containers/storage/drivers/devmapper master
github.com/containers/storage/drivers master
github.com/containers/storage/drivers/overlay2 master
github.com/containers/storage/drivers/overlay master
github.com/containers/storage/drivers/register master
github.com/containers/storage/drivers/vfs master
github.com/containers/storage/drivers/zfs master
github.com/containers/storage/pkg/archive master
github.com/containers/storage/pkg/chrootarchive master
github.com/containers/storage/pkg/devicemapper master
github.com/containers/storage/pkg/directory master
github.com/containers/storage/pkg/fileutils master
github.com/containers/storage/pkg/homedir master
github.com/containers/storage/pkg/idtools master
github.com/containers/storage/pkg/ioutils master
github.com/containers/storage/pkg/loopback master
github.com/containers/storage/pkg/mount master
github.com/containers/storage/pkg/parsers/kernel master
github.com/containers/storage/pkg/parsers master
github.com/containers/storage/pkg/pools master
github.com/containers/storage/pkg/promise master
github.com/containers/storage/pkg/random master
github.com/containers/storage/pkg/reexec master
github.com/containers/storage/pkg/stringid master
github.com/containers/storage/pkg/system master
github.com/containers/storage/storage master
github.com/containers/storage/storageversion master
github.com/docker/distribution/context master
github.com/docker/distribution/digestset master
github.com/docker/distribution master
github.com/docker/distribution/reference master
github.com/docker/distribution/registry/api/errcode master
github.com/docker/distribution/registry/api/v2 master
github.com/docker/distribution/registry/client/auth/challenge master
github.com/docker/distribution/registry/client master
github.com/docker/distribution/registry/client/transport master
github.com/docker/distribution/registry/storage/cache master
github.com/docker/distribution/registry/storage/cache/memory master
github.com/docker/distribution/uuid master
github.com/docker/distribution/vendor/github.com/gorilla/context master
github.com/docker/distribution/vendor/github.com/gorilla/mux master
github.com/docker/distribution/vendor/github.com/opencontainers/go-digest master
github.com/docker/distribution/vendor/github.com/Sirupsen/logrus master
github.com/docker/distribution/vendor/golang.org/x/net/context master
github.com/docker/engine-api/client master
github.com/docker/engine-api/client/transport/cancellable master
github.com/docker/engine-api/client/transport master
github.com/docker/engine-api/types/blkiodev master
github.com/docker/engine-api/types/container master
github.com/docker/engine-api/types/filters master
github.com/docker/engine-api/types master
github.com/docker/engine-api/types/mount master
github.com/docker/engine-api/types/network master
github.com/docker/engine-api/types/reference master
github.com/docker/engine-api/types/registry master
github.com/docker/engine-api/types/strslice master
github.com/docker/engine-api/types/swarm master
github.com/docker/engine-api/types/time master
github.com/docker/engine-api/types/versions master
github.com/docker/go-connections/nat master
github.com/docker/go-connections/sockets master
github.com/docker/go-connections/tlsconfig master
github.com/docker/go-units master
github.com/docker/libtrust master
github.com/ghodss/yaml master
github.com/golang/glog master
github.com/imdario/mergo master
github.com/mattn/go-runewidth master
github.com/mistifyio/go-zfs master
github.com/mtrmac/gpgme master
github.com/opencontainers/go-digest master
github.com/opencontainers/image-spec/specs-go master
github.com/opencontainers/image-spec/specs-go/v1 master
github.com/opencontainers/runc/libcontainer/label master
github.com/opencontainers/runc/libcontainer/system master
github.com/opencontainers/runc/libcontainer/user master
github.com/pborman/uuid master
github.com/pkg/errors master
github.com/Sirupsen/logrus master
github.com/vbatts/tar-split/archive/tar master
github.com/vbatts/tar-split/tar/asm master
github.com/vbatts/tar-split/tar/storage master
golang.org/x/net/context master
golang.org/x/net/http2/hpack master
golang.org/x/net/http2 master
golang.org/x/net/idna master
golang.org/x/net/lex/httplex master
golang.org/x/net/proxy master
gopkg.in/cheggaaa/pb.v1 master
gopkg.in/yaml.v2 master
k8s.io/apimachinery/pkg/util/errors master
k8s.io/apimachinery/pkg/util/net master
k8s.io/apimachinery/pkg/util/sets master
k8s.io/kubernetes/pkg/util/homedir master
```

**Comment by LK4D4** [comment]
This was fixed.
